### ISSUE TITLE
When try to find rootfile config, the application throws a maxium call stack error

### ISSUE THREAD

**Issue by ByIvo** [ByIvo/project-info#1]
It probabily happens because the path under comparision is including the config file name, so the next directory is never empty (the exit loop clause), even when reaches the root system path (e.g C:\ ; /)

Stack trace:
```bash
RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at posixSplitPath (path.js:411:27)
    at Object.posix.parse (path.js:591:18)
    at getUpwardsDirectory (/any/path/project-info/src/configfile_finder/rootfile-finder.js:20:15)
    at keepLookingUpwards (/any/path/project-info/src/configfile_finder/rootfile-finder.js:38:23)
    at findConfigfileIn (/any/path/project-info/src/configfile_finder/rootfile-finder.js:33:12)
    at keepLookingUpwards (/any/path/project-info/src/configfile_finder/rootfile-finder.js:41:12)
    at findConfigfileIn (/any/path/project-info/src/configfile_finder/rootfile-finder.js:33:12)
    at keepLookingUpwards (/any/path/project-info/src/configfile_finder/rootfile-finder.js:41:12)
    at findConfigfileIn (/any/path/project-info/src/configfile_finder/rootfile-finder.js:33:12)
    at keepLookingUpwards (/any/path/project-info/src/configfile_finder/rootfile-finder.js:41:12)
```

**Comment by ByIvo** [comment]
The error happened because the condition to stay seeking was just if the boolean evaluation on nextDirectory variable was true... when you parse a system root path, you still getting itself and not a empty string, as expected before.

The correct piece of code now is like this: 

```javascript
var upwardsParsed = getUpwardsDirectory(fromPath);

  var nextDirectory = upwardsParsed.dir;
  var rootFilesystemPath = upwardsParsed.root;

  if(nextDirectory !== rootFilesystemPath) {
    return findConfigfileIn(nextDirectory, configFilename);
  } else {
    throw Error('It was not able to find a file named ' + configFilename + ' in any upwards directory.');
  }
```
